### ISSUE TITLE
Support for multiple naming conventions and custom property->query parameter mapping

### ISSUE THREAD

**Issue by NotIlya4** [Victorvhn/uri-query-string-composer#4]
Hello, please add support for varios cases eg `camelCase`, `kebab-case`. Or even better if you give ability to provide custom `Property name` -> `Query parameter name` mapper

**Comment by Victorvhn** [comment]
I've just pushed an update to make it possible. See if it works for you.

You can check [this](https://github.com/Victorvhn/uri-query-string-composer#global-configuration) section to configure a key case style for the entire application or you can check [this](https://github.com/Victorvhn/uri-query-string-composer#querystringkeycasestyleattribute) section to configure by property.

Feel free to send updates if needed 😁
